title: "EC"
url: ""

# Author
author:
  name: "Edmund Chege"
  avatar: "/assets/images/profile.png"
  bio: "Infrastructure | Security Engineer"
  location: "Nairobi, Kenya"
  links:
    - label: "Website"
      icon: "fas fa-globe"
      url: "https://edmundchege.github.io"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/edmundchege"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/edmundchege"

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:path/
  talks:
    output: true
    permalink: /talks/:path/

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: single
      author_profile: false
      share: false
  - scope:
      path: ""
      type: "talks"
    values:
      layout: single
      author_profile: false
      share: false

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-seo-tag

# Theme settings
paginate: 5
paginate_path: "/page:num/"
include: ["_pages"]
