title: "Edmund Chege"
subtitle: "Infrastructure Engineer | Orchestration & Security Enthusiast"
name: "Edmund Chege"
description: "From bare metal infrastructure to consumer land — building secure, reliable, and scalable systems."
logo: "/assets/images/profile.png"
url: "https://edmundchege.github.io"

# Theme
remote_theme: "mmistakes/minimal-mistakes@4.26.1"

# Author
author:
  name: "Edmund Chege"
  avatar: "/assets/images/profile.png"
  bio: "Infrastructure Engineer | Kubernetes | Terraform | Security"
  location: "Nairobi, Kenya"
  links:
    - label: "Website"
      icon: "fas fa-globe"
      url: "https://edmundchege.github.io"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/edmundchege"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/edmundchege"
    - label: "Twitter"
      icon: "fab fa-twitter"
      url: "https://twitter.com/edmundchege"

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:path/
  talks:
    output: true
    permalink: /talks/:path/

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: single
      author_profile: false
      share: false
  - scope:
      path: ""
      type: "talks"
    values:
      layout: single
      author_profile: false
      share: false

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

# Theme settings
paginate: 5
paginate_path: "/page:num/"
include: ["_pages"]
